alias be='cd /home/app/aa-be && git pull && gradle bootJar && pm2 restart be'
alias fe='cd /home/app/aa-fe && git pull && yarn && yarn build:dev && pm2 restart fe'
alias admin='cd /home/app/aa-admin && git pull && yarn && yarn build:dev'

alias conf-nginx='vim /etc/nginx/conf.d/default.conf'
alias conf-bash='vim ~/.bashrc'

source ~/.bashrc;

//////////// real

alias fe='cd /home/ec2-user/nc-blog-fe && pm2 restart fe'
alias be='cd /home/ec2-user/nt-be && pm2 restart be'

alias update-fe='cd /home/ec2-user/nc-blog-fe && git pull && yarn && yarn build:prod && pm2 restart fe'
alias update-admin='cd /home/ec2-user/nc-blog-admin && git pull && yarn && yarn build:prod'

alias db='mysql -u admin -h bgl-asrds001.cd2khxk8iq8j.ap-northeast-2.rds.amazonaws.com -p -P 62222'

alias conf-nginx='sudo vim /etc/nginx/conf.d/default.conf'
alias conf-bash='vim ~/.bashrc'