server {
    listen      80;
    server_name aaarchigroup.com;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen       443 ssl;
    server_name  aaarchigroup.com;
    ssl_certificate "/etc/nginx/ssl/chained.crt";
    ssl_certificate_key "/etc/nginx/ssl/private.key";
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;
    ssl_ciphers PROFILE=SYSTEM;
    ssl_prefer_server_ciphers on;
    client_max_body_size 500M;

    location /api {
        proxy_pass http://27.102.141.132:9450; //L4로 묶어놓았다고 하신거 같은데 어떤경로로 해야할지 몰라서 일단 경로는 하나만 넣었습니다
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location = /admin {
        return 301 /admin/;
    }

    location ^~ /admin/ {
        alias /스토리지 서버 경로/aa-admin/;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    location ^~ /files/ {
        alias /스토리지 서버 경로/files/;
    }

    location / {
        proxy_pass http://27.102.141.132:9550; //L4로 묶어놓았다고 하신거 같은데 어떤경로로 해야할지 몰라서 일단 경로는 하나만 넣었습니다
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}