server {
    listen      80;
    server_name aa.newtype.design;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen       443 ssl;
    server_name  aa.newtype.design;
    ssl_certificate "/etc/nginx/ssl/newtype-chained.crt";
    ssl_certificate_key "/etc/nginx/ssl/newtype-private.key";
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;
    ssl_ciphers PROFILE=SYSTEM;
    ssl_prefer_server_ciphers on;
    client_max_body_size 500M;

    location /api {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location = /admin {
        return 301 /admin/;
    }

    location ^~ /admin/ {
        alias /home/aaarchigroup/aa-admin/;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    location ^~ /files/ {
        alias /home/aaarchigroup/files/;
    }

    location / {
        proxy_pass http://127.0.0.1:9000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}